changed Jenkiksfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,22 +1,59 @@
-pipeline {
+pipeline{
     agent any
-    
-    
-    stages {
-        stage('up') {
-            steps {
-                sh 'docker-compose up -d'
-            }
-        }
-       
+    parameters {
+        string defaultValue: 'master', description: 'Provide Branch Name', name: 'BRANCH'
     }
-    post {
-  success {
-    echo 'success'
-  }
-  failure {
-    echo 'failure'
-  }
-}
 
+    stages{
+        stage("Checkout"){
+            steps{
+                echo "========executing Checkout========"
+                script{
+                    sh(script: "git checkout ${BRANCH}")
+                }
+            }
+            
+        }
+        stage("Deploy"){
+            steps{
+                echo "========executing Deploy========"
+                script{
+                    
+                    sh(script:"ssh -o StrictHostKeyChecking=no  ubuntu@100.26.187.220 \"mkdir -p /home/ubuntu/compose-deployment-2/ \" ")
+                    sh(script:"scp -r ${WORKSPACE}/* ubuntu@100.26.187.220:/home/ubuntu/compose-deployment-2/ ")
+                    sh(script:"ssh -o StrictHostKeyChecking=no  ubuntu@100.26.187.220 \"cd /home/ubuntu/compose-deployment-2/ && sudo docker-compose up -d \" ")
+                }
+                
+            }
+            
+        }
+        stage("Status"){
+            steps{
+                echo "========executing Status========"
+                script{
+                    sh '''#!/bin/bash
+                   echo "this will work"
+                   RESULT=$?
+                   if [ $RESULT -eq 0 ]; then
+                   echo "success"
+                   else
+                   echo "failed"
+                   fi
+                   '''
+                }
+            }
+            
+        }
+    }
+    post{
+        always{
+            echo "========always========"
+        }
+        success{
+            echo "========pipeline executed successfully ========"
+        }
+        failure{
+            echo "========pipeline execution failed========"
+        }
+    }
 }
